services:
  - type: web
    name: DemoDomainTestProject
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn DemoDomainTestProject.wsgi:application"
    staticPublishPath: staticfiles
